version: '3.8'

services:
  # RabbitMQ Broker Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cfx-broker
    ports:
      - "5672:5672"   # Port for your backend to connect
      - "15672:15672"  # Port for the Management Web UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # InfluxDB Database Service
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"   # Port for your backend and the Web UI
    volumes:
      - influxdb_data:/var/lib/influxdb2

# Docker volumes to persist data
volumes:
  rabbitmq_data:
  influxdb_data: